services:
  - type: web
    name: pesaflow-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: python manage.py migrate && python manage.py ensure_admin && gunicorn pesaflow.wsgi:application
    healthCheckPath: /api/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pesaflow-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://pesaflow-frontend.vercel.app"
      - key: MPESA_ENVIRONMENT
        value: "sandbox"
      - key: ADMIN_EMAIL
        value: "admin@gmail.com"
      - key: ADMIN_PHONE
        value: "0723274962"
      - key: ADMIN_FULL_NAME
        value: "Myles Munroe"
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: pesaflow-db
    plan: free
