# Generated by Django 4.2.8 on 2026-08-27 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dashboardlog",
            new_name="admin_dashb_action_05dc7a_idx",
            old_name="admin_dashb_action_89d47e_idx",
        ),
    ]
