# Generated by Django 4.2.8 on 2026-08-27 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_sender__f6dfae_idx",
            old_name="transactions_sender__c4b9f4_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_recipie_6e87f2_idx",
            old_name="transactions_recipi_eb6fc1_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_status_d2f80b_idx",
            old_name="transactions_status_cdf5b5_idx",
        ),
    ]
